### ISSUE TITLE
New Badge- getting error with require

### ISSUE THREAD

**Issue by bretonics** [badges/badgerbadgerbadger#66]
I'm trying to include a new [size badge] (https://github.com/ruddfawcett/reposs) I really like, but after building and installing the gem locally I get this error:
>require: cannot load such file -- badger/size (LoadError)

I added a size.rb file in /lib/badger/size.rb, which just adds the owner and repo to the badge string, and added `require 'badger/size'` to the /lib/badger.rb file.

My ruby is basic, but I can see that the build is not including my new size.rb file. I ran this to check:
>gem contents --no-prefix badgerbadgerbadger | grep lib
lib/badger.rb
lib/badger/badge.rb
lib/badger/badger.rb
lib/badger/bonus.rb
lib/badger/cli.rb
lib/badger/config.rb
lib/badger/helpers.rb
lib/badger/license.rb
lib/badger/rubygem.rb
lib/badger/service.rb
lib/badger/version.rb

I think it will be a pretty cool extra badge to add to your code. Thanks!

**Comment by pikesley** [comment]
Do you have a pull-request for what you did please?

**Comment by bretonics** [comment]
Hi, sorry for the delay.

I was just about to commit and for some reason now the size file is included, but it doesn't work, so I'm making the pull request and you can give me your advice/opinion. I am sure I forgot to add something somewhere to print it.
